name: documentation-builder
version: '1.0.0-rc6'
summary: Build HTML documentation from markdown
description: |
  A tool to build repositories of markdown files of documentation into HTML pages

grade: stable
confinement: strict

parts:
  repo:
    plugin: python
    source: .
  copy:
    plugin: dump
    source: bin

apps:
  documentation-builder:
    plugs:
        - home
    command: documentation-builder
